from ast import Raise
from xml.dom import ValidationErr
from odoo import http , _
from odoo.http import request
import logging
from datetime import date, timedelta
import calendar
_logger = logging.getLogger(__name__)
from odoo.addons.portal.controllers.portal import CustomerPortal, pager as portal_pager
from odoo.addons.project.controllers.portal import ProjectCustomerPortal 

class ProjectCustomerPortal(ProjectCustomerPortal):

    # @http.route(['/my/tasks/<int:task_id>'], type='http', auth="public", website=True)
    # def portal_my_task(self, task_id, report_type=None, access_token=None, project_sharing=False, **kw):
    #     try:
    #         task_sudo = self._document_check_access('project.task', task_id, access_token)
    #     except (AccessError, MissingError):
    #         return request.redirect('/my')

    #     if report_type in ('pdf', 'html', 'text'):
    #         return self._show_task_report(task_sudo, report_type, download=kw.get('download'))

    #     # ensure attachment are accessible with access token inside template
    #     for attachment in task_sudo.attachment_ids:
    #         attachment.generate_access_token()
    #     if project_sharing is True:
    #         # Then the user arrives to the stat button shown in form view of project.task and the portal user can see only 1 task
    #         # so the history should be reset.
    #         request.session['my_tasks_history'] = task_sudo.ids
    #     values = self._task_get_page_view_values(task_sudo, access_token, **kw)
    #     return request.render("project.portal_my_task", values)

    @http.route(['/my/tasks', '/my/tasks/page/<int:page>'], type='http', auth="user", website=True)
    def portal_my_tasks(self, page=1, date_begin=None, date_end=None, sortby=None, filterby=None, search=None, search_in='name', groupby=None, **kw):
        searchbar_filters = self._get_my_tasks_searchbar_filters()
        today = date.today()
        first_day = today.replace(day=1)
        last_day = today.replace(day=calendar.monthrange(today.year, today.month)[1])

        # closed_stages = request.env['subscription.package.stage'].sudo().search([('category', '=', 'closed')],limit=1)

        _logger.info("--------- request.env.user.partner_id.id %s",request.env.user.partner_id.id)
        subscription_package = request.env['subscription.package'].sudo().search([
            ('partner_id','=',request.env.user.partner_id.id),
            ('start_date','>=',first_day),
            ('next_invoice_date', '<=', last_day),
            ('stage_id.category','=','progress')
        ])
        subscription_package_tasks = None
        if subscription_package:
            subscription_package = subscription_package
            subscription_package_tasks = subscription_package.task_ids

        _logger.info("--- subscription_package_tasks ---- %s",subscription_package_tasks)

        if not filterby:
            filterby = 'all'
        domain = searchbar_filters.get(filterby, searchbar_filters.get('all'))['domain']

        values = self._prepare_tasks_values(page, date_begin, date_end, sortby, search, search_in, groupby, domain=domain)

        # pager
        pager_vals = values['pager']
        pager_vals['url_args'].update(filterby=filterby)
        pager = portal_pager(**pager_vals)
        grouped_tasks = values['grouped_tasks'](pager['offset'])

        # insted of grouped_tasks for this module we use subscription_package_tasks
        values.update({
            'grouped_tasks': subscription_package_tasks,
            'show_project': True,
            'pager': pager,
            'searchbar_filters': searchbar_filters,
            'filterby': filterby,
            'subscription_package' : subscription_package
        })
        _logger.info("------- project.portal_my_tasks ------------- %s",values)
        return request.render("project.portal_my_tasks", values)

    def _prepare_tasks_values(
        self, page, date_begin, date_end, sortby, search, search_in, groupby,
        url="/my/tasks", domain=None, su=False, project=False
    ):
        # Call original method
        values = super()._prepare_tasks_values(
            page, date_begin, date_end, sortby, search, search_in, groupby,
            url=url, domain=domain, su=su, project=project
        )

        # 👇 Get the groupby dictionary generated by your overridden _task_get_searchbar_groupby
        searchbar_groupby = values.get('searchbar_groupby', {})

        # 👇 If current groupby key doesn't exist anymore (e.g. project_id removed)
        if values.get('groupby') not in searchbar_groupby:
            _logger.warning(
                f"Groupby '{values.get('groupby')}' not found in searchbar_groupby. Resetting to 'none'."
            )
            values['groupby'] = 'none'

            # Also update pager args to avoid broken URL reloads
            pager = values.get('pager', {})
            if 'url_args' in pager:
                pager['url_args']['groupby'] = 'none'
                values['pager'] = pager

        return values      

    def _task_get_searchbar_groupby(self, milestones_allowed, project=False):
        _logger.info("---- from custom modules _task_get_searchbar_groupby ------")
        values = {
            'none': {'label': _('None'), 'sequence': 10},
            # 'stage_id': {'label': _('Stage'), 'sequence': 20},
            'state': {'label': _('Status'), 'sequence': 40},
            'priority': {'label': _('Priority'), 'sequence': 60},
            'partner_id': {'label': _('Customer'), 'sequence': 70},
            'alt_subscription_id' : {'label': _('Subscription Id'), 'sequence': 80}
        }
        # if not project:
        #     values['project_id'] = {'label': _('Project'), 'sequence': 30}
        if milestones_allowed:
            values['milestone_id'] = {'label': _('Milestone'), 'sequence': 50}

        return values
    
class AltSupportBridgeServerActionTask(http.Controller):

    @http.route('/task/change/request/<int:change_request_id>/confirm', type='http', auth='public')
    def confirm_change_request_id(self, change_request_id):
        if not change_request_id:
            return
        
        change_request_table = request.env['change.request.task'].sudo()
        change_request_id = change_request_table.browse(change_request_id)
        if not change_request_id.exists():
            return
        
        if change_request_id.state == 'Pending':

            change_req_time = change_request_id.time
            subs_time = sum(change_request_id.task_id.alt_subscription_id.product_line_ids.mapped('product_qty'))
            used_time = sum(change_request_id.task_id.alt_subscription_id.task_ids.mapped('effective_hours'))
            task_alloc_time = sum(change_request_id.task_id.alt_subscription_id.task_ids.mapped('allocated_hours'))
            _logger.info("--- change_req_time , subs_time , used_time , task_alloc_time %s, %s, %s, %s",change_req_time, subs_time, used_time, task_alloc_time)

            if used_time <= 0.00 :
                new_time = change_req_time 
            else:
                new_time = (subs_time - used_time) - change_req_time 

            _logger.info("------ new line time %s",abs(new_time))

            change_request_id.write({'state': 'Approved'})
            change_request_id.task_id.write({
                'state' : '03_approved',
                'allocated_hours' : change_request_id.task_id.allocated_hours + abs(new_time)
            })

            new_allocation_time = sum(change_request_id.task_id.alt_subscription_id.task_ids.mapped('allocated_hours'))
            if new_allocation_time > subs_time:
                change_request_id.task_id.alt_subscription_id.write({
                    'product_line_ids' : [(0, 0,{
                        'product_id' :  change_request_id.task_id.alt_subscription_id.product_line_ids[0].product_id.id,
                        # 'product_qty' : change_request_id.time - (change_request_id.task_id.alt_subscription_id.product_line_ids.mapped('product_qty')[0] - change_request_id.task_id.alt_subscription_id.task_ids.mapped('effective_hours')[0]),
                        'product_qty' : abs(new_time)

                    })]
                })

            change_request_id.task_id.message_post(body="Change Request Is Accedpted By Client")
        
        last_url = request.httprequest.referrer or '/my/tasks'
        return request.redirect(last_url)
 
    @http.route('/task/change/request/<int:change_request_id>/reject', type='http', auth='public')
    def reject_change_request_id(self, change_request_id):
        if not change_request_id:
            return
        
        change_request_table = request.env['change.request.task'].sudo()
        change_request_id = change_request_table.browse(change_request_id)
        if not change_request_id.exists():
            return
        
        if change_request_id.state == 'Pending':
            change_request_id.write({'state': 'Cancelled'})
            change_request_id.task_id.write({
                'state' : '01_in_progress',
            })
            change_request_id.task_id.message_post(body="Change Request Is Rejected By Client")
        
        last_url = request.httprequest.referrer or '/my/tasks'
        return request.redirect(last_url)

    @http.route('/task/<int:task_id>/confirm', type='http', auth='public')
    def confirm_task(self, task_id):
        if not task_id:
            return
        
        task_table = request.env['project.task'].sudo()
        task_id = task_table.browse(task_id)
        if not task_id.exists():
            return
        
        if task_id.state != '03_approved':

            task_id.write({'state': '03_approved'})
            # move_stage = request.env['project.task.type'].sudo().search([
            #     ('name', 'ilike', 'client confirm'),
            #     ('project_ids', 'in', [task_id.project_id.id])
            # ], limit=1)

            # if move_stage:
        
        last_url = request.httprequest.referrer or '/my/tasks'
        return request.redirect(last_url)

    @http.route('/task/<int:task_id>/reject', type='http', auth='public')
    def reject_task(self, task_id):
        if not task_id:
            return
        task_table = request.env['project.task'].sudo()
        task_id = task_table.browse(task_id)
        if not task_id.exists():
            return
        
        if task_id.state != '1_canceled':

            task_id.write({'state': '1_canceled'})
            # move_stage = request.env['project.task.type'].sudo().search([
            #     ('name', 'ilike', 'done'),
            #     ('project_ids', 'in', [task_id.project_id.id])
            # ], limit=1)

            # if move_stage:

        last_url = request.httprequest.referrer or '/my/tasks'
        return request.redirect(last_url)
    
    @http.route('/task/<int:task_id>/finished', type='http', auth='public')
    def finished_task(self, task_id):
        if not task_id:
            return
        task_table = request.env['project.task'].sudo()
        task_id = task_table.browse(task_id)
        if not task_id.exists():
            return
        
        if task_id.state != '05_finished':

            task_id.write({'state': '05_finished'})
            # task_id.message_post(body="Change Request Is Rejected By Client")
            # move_stage = request.env['project.task.type'].sudo().search([
            #     ('name', 'ilike', 'done'),
            #     ('project_ids', 'in', [task_id.project_id.id])
            # ], limit=1)

            # if move_stage:

        last_url = request.httprequest.referrer or '/my/tasks'
        return request.redirect(last_url)


            
        
    
        

        

    
    