{
    'name': 'Shopify Connector (GraphQL)',
    'version': '1.0.0',
    'category': 'Managment',
    'author': 'Prefortune Technologies',
    'sequence': -100,
    'summary': 'Managment System',
    'description': """""",
    'license': 'LGPL-3',
    'depends': [
        'base',
        'sale_management',
        'sale_loyalty',
        'stock',
        'mrp',
        'point_of_sale',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/cron.xml',
        'views/menu.xml',
        'views/connector.xml',
        'views/product.xml',
        'views/res_partner.xml',
        'views/sale_order.xml',
        'views/queue.xml',
        'wizards/shopify_operation_wizard_view.xml',
    ],
    'demo': [],
    'application': True,
    'auto_install': False,
}
